apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
spec:
  selector:
    k8s-app: fluent-bit
    version: v1
    kubernetes.io/cluster-service: "true"

  ports:
    - port: 5170
      targetPort: 5170
    
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: fluent-bit
  namespace: mvnr-paas
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: fluent-bit-read
rules:
- apiGroups: [""]
  resources:
  - namespaces
  - pods
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: fluent-bit-read
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fluent-bit-read
subjects:
- kind: ServiceAccount
  name: fluent-bit
  namespace: mvnr-paas
