apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  labels:
    k8s-app: fluent-bit
    kubernetes.io/cluster-service: "true"
    version: v1
  name: fluent-bit-test
  namespace: mvnr-paas
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: fluent-bit
      kubernetes.io/cluster-service: "true"
      version: v1
  template:
    metadata:
      annotations:
        prometheus.io/path: /api/v1/metrics/prometheus
        prometheus.io/port: "2020"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        k8s-app: fluent-bit
        kubernetes.io/cluster-service: "true"
        version: v1
    spec:
      containers:
      - env:
        - name: REMOTE_HOST
          value: fluentd-aggregator.mvnr-paas.svc.cluster.local
        - name: REMOTE_PORT
          value: "24224"
        - name: FLUENT_ELASTICSEARCH_HOST
          value: elasticsearch.mvnr-paas.svc.cluster.local
        - name: FLUENT_ELASTICSEARCH_PORT
          value: "9200"
        image: fluent/fluent-bit:1.0.4-debug
        imagePullPolicy: Always
        name: fluent-bit
        ports:
        - containerPort: 2020
          protocol: TCP
        resources:
          limits:
            cpu: "1"
            memory: 300Mi
          requests:
            cpu: "1"
            memory: 300Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /fluent-bit/etc/
          name: fluent-bit-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: fluent-bit
      serviceAccountName: fluent-bit
      terminationGracePeriodSeconds: 10
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
      volumes:
      - configMap:
          defaultMode: 420
          name: fluent-bit-config
        name: fluent-bit-config
  templateGeneration: 30
  updateStrategy:
    type: OnDelete
