apiVersion: v1
kind: Service
metadata:
  name: fluent-bit
spec:
  selector:
    k8s-app: fluent-bit
    version: v1
    kubernetes.io/cluster-service: "true"

  ports:
    - port: 5170
      targetPort: 5170
